version: "3.9"

services:
  dash:
    build:
      context: .
      dockerfile: Dockerfile
    image: amplify:latest
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #           - gpu
    ports:
      - 80:80
    volumes:
      - /home/samsipe/clearml.conf:/root/clearml.conf
    restart: always
    user:
      "root"
    command: "gunicorn -b 0.0.0.0:80 app:server"
