version: "3.9"

services:
  # reverse-proxy:
  #   image: nginx:latest
  #   depends_on:
  #       - dash-app
  #   volumes:
  #     - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80

  dash-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: amplify:latest
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #           - gpu
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - /home/ubuntu/clearml.conf:/root/clearml.conf
    restart: on-failure
    user: "root"
    command: "gunicorn -b 0.0.0.0:80 app:server"
